services:
    postgres:
       image: postgres:16
       container_name: puskesmas-database
       restart: unless-stopped
       environment:
          POSTGRES_USER: puskesmas
          POSTGRES_PASSWORD: puskesmasBahaya12
          POSTGRES_DB: database_puskesmas
       ports:
         - "5432:5432"
       volumes:
         - postgres_data:/var/lib/postgresql/data
         
    

volumes:
   postgres_data: